### ISSUE TITLE
Thank you for the TypeScript ECS posts!

### ISSUE THREAD

**Issue by mdwheele** [mbforbes/fallgate#1]
Hey @mbforbes!

I just wanted to reach out and show some appreciation for the posts you made a few years ago on your journey with Entity Component Systems through work on Fallgate.

I recently decided to come back to hobby game development and wanted to give the web a shot! So I'm building out a framework currently to produce a riff on the multiplayer top-down survival shoot-em-up genre. 

I got a lot of inspiration for different ways to handle combat systems through a few things you hinted at in the blog posts. However, I am curious to see a more complete picture. Is there any chance you would offer original TypeScript source under a restrictive license that made it available for educational purposes? 

I'm personally planning on maintaining my current discovery work as an open-source project to give students/hobbyists another example of the many different ways to go about development of a game. 

I'm happy to discuss here, but if you'd rather talk over email I have it listed on my [GitHub Profile](https://github.com/mdwheele)

Again, thanks so much for publishing those articles a few years ago!

**Comment by mbforbes** [comment]
Hey @mdwheele , thank you so much for your kind words, and for opening this! I'm sorry for the glacier-speed reply. 

I think this is a great idea. I'd like to check in with @ctschmidlak to see what he thinks, too, as the other 1/2 of the project. What do you think, Cooper?

I had forgotten how this worked exactly, and looking now, it does seem that this repo already has [the unobfuscated source](https://github.com/mbforbes/fallgate/blob/master/docs/build/game.js), as well as all the assets, so publishing the TypeScript wouldn't be a significant change in terms of visibility. (Plus the game has already been copy/pasted onto a bunch of websites.) And I can imagine having the TypeScript and the file structure being helpful for those wanting to read it.

The only limiting factor in my mind would be the time. Providing the source would imply to someone stumbling upon the repository that you could actually build the game, but this would take investment (I am so terrible at getting TypeScript environments all setup correctly, etc.). So if we decide to do this maybe we just dump it in and worry the build when the time comes (i.e., if anyone ever cares).

**Comment by CTSchmidlak** [comment]
No concerns on my end @mbforbes, I would be happy to see Fallgate live on in some way that is beneficial to other indie/hobbyist devs!

**Comment by mbforbes** [comment]
Sounds good then! I will take this on as a TODO.

**Comment by mbforbes** [comment]
This is finished — the source code is now in `src/`. Maybe this will inspire me to finally get around to finishing up that post series now 😄
